### ISSUE TITLE
config problem

### ISSUE THREAD

**Issue by pikatfu** [hotcereal/cloud-saves-miyoo-mini-plus#2]
Run 
/mnt/SDCARD/rclone config
>>>
▒: not found
/mnt/SDCARD/rclone: line 2: syntax error: unexpected "("
/ #

**Comment by RoninTurkey** [comment]
> Run /mnt/SDCARD/rclone config
> 
> > > >
> 
> ▒: not found /mnt/SDCARD/rclone: line 2: syntax error: unexpected "(" / #

I have the same issue.

**Comment by Hollyrious** [comment]
same.

**Comment by ChristinWhite** [comment]
I was also having trouble with it until I saw #1. Using the correct binary solved the issue for me.

**Comment by Hollyrious** [comment]
Using that binary changed nothing for me.

**Comment by Hollyrious** [comment]
Using the ARM v6 64bit binary fixed it. https://downloads.rclone.org/v1.64.0/rclone-v1.64.0-linux-arm-v6.zip

**Comment by UScr00ge** [comment]
I'm getting the following error running rclone from the arm v6 zip

```
./rclone: line 1: ELFkt����������$����������⸮0�@���]����0���������������Q�Q����-����t@��=�q��p��o�묰��呲��!a�����9: not found
./rclone: line 2: ���-�: not found
./rclone: line 3: syntax error: unexpected "("
```

**Comment by nicktheone** [comment]
> I'm getting the following error running rclone from the arm v6 zip
> 
> ```
> ./rclone: line 1: ELFkt����������$����������⸮0�@���]����0���������������Q�Q����-����t@��=�q��p��o�묰��呲��!a�����9: not found
> ./rclone: line 2: ���-�: not found
> ./rclone: line 3: syntax error: unexpected "("
> ```

Try to remove and download again the binaries, as they should work flawlessly (just done it).

**Comment by Otaku-Punk** [comment]
I had the same error, using the rclone file from [this link](https://downloads.rclone.org/v1.62.2/rclone-v1.62.2-linux-arm-v7.zip) instead solved my issue.

Credit to Reddit user "[GabePlaysDrums](https://www.reddit.com/user/GabePlaysDrums/)" for the solution
[Reddit thread](https://www.reddit.com/r/MiyooMini/comments/13gvh5n/app_three_onion_apps_to_get_cloud_saves_onoff_the/)

**Comment by notmayo** [comment]
To anyone looking for an answer to this, I just successfully followed the guide and had this error initially. Use this binary: https://downloads.rclone.org/v1.64.2/rclone-v1.64.2-linux-arm-v7.zip

**Comment by hotcereal** [comment]
This late as hell fix is due to me accidentally or somehow linking to the macOS version of rclone prior to about a week ago. This should be resolved by now thanks to users like notmayo above.

The binary linked in the project is correct now.

**Comment by pumpkinlink** [comment]
@hotcereal the second link on the readme is still wrong, i made a PR: #9
